### DISCUSSION TITLE
Visualizers

### DISCUSSION THREAD

**Discussion by gcelano** [korpling/ANNIS#872] [General]
It is not clear to me how to change my `corpus-config.toml` so that I can avoid displaying some annotation layer. For example, the morphological feature "case" is displayed for all tokens: is it possible to disable it? 

Moreover, the anno annotation (metadata) can be accessed by clicking on the "i" of each result: is it possible to show some of them explicitly?

**Comment by thomaskrause** [comment]
I assume you use the KWIC visualizer for the tokens, which is a grid visualizer in disguise. As such, you can configure it to only show a specific list of annotations (and implicitly not show any non-given annotation layers using the `annos` mapping: <https://korpling.github.io/ANNIS/4/user-guide/import-and-config/visualizations-list.html#grid>

```toml
[[visualizers]]
vis_type = "kwic"
display_name = "kwic"
visibility = "permanent"

[visualizers.mappings]
annos = "/tiger::lemma/,/tiger::pos/"
```
The `annos` mapping is a list of regular expressions (including the namespace) which must match so the annotation is shown.

There is currently no way of excluding metadata from the information window, but you can sort the order: <https://korpling.github.io/ANNIS/4/user-guide/import-and-config/corpus-config.html#order-of-metadata-annotations>
