### ISSUE TITLE
Processing time for some queries

### ISSUE THREAD

**Issue by gcelano** [korpling/ANNIS#881]
There are a few queries that require a long processing time and during which the server becomes so busy that cannot accept further ANNIS queries. For Example, the following query takes minutes because of `.*` (but note that it is limited by `@* author="Homer"` and I was expecting it to be rather fast):
```
pos="n" ->dep[dep_fnc="ATR"] pos="n" & #1 ->dep[dep_fnc="ATR"] pos="l" 
& #2 .* #1 & #3 .* #2 &  case="g" _ident_ #2 @* author="Homer"
```
while the following is very fast:
```
pos="n" ->dep[dep_fnc="ATR"] pos="n" & #1 ->dep[dep_fnc="ATR"] pos="l" 
& #2 .1,3 #1 & #3 .1,3 #2 &  case="g" _ident_ #2 @* author="Homer"
```
More in general, it would helpful if there were a way to limit processing time/absorbtion of resources, even if this means that the results cannot be returned. A "stop button" would also be helpful, in case one notices that ANNIS is taking too much time.

**Comment by thomaskrause** [comment]
A stop button is something that has been on the TODO-list for a long time but was difficult to implement due to the limitations of the current REST API. But there is a `query_timeout` setting in the `[database]` section which was not documented yet but would help to avoid endless queries (the documentation will be fixed in the next release)

```toml
[database]
graphannis = "data/"
sqlite = "service.sqlite"
# Optional timeout for queries in seconds. No timeout is applied if parameter is
# not given.
query_timeout = 60
```

I am still investigating why these queries take forever to execute, but I can reproduce these issues on the oga_v0.2.0_1 corpus
